-- Database create.
CREATE DATABASE walmart_db;

-- Table imoported using " Table data import wizard".

-- Understanding Data. 
SELECT * FROM walmart;

SELECT COUNT(*) FROM walmart;

SELECT *
FROM walmart
WHERE invoice_id IS NULL
OR Branch IS NULL
OR City IS NULL
OR category IS NULL
OR unit_price IS NULL
OR quantity IS NULL
OR date IS NULL
OR time IS NULL
OR payment_method IS NULL
OR rating IS NULL
OR profit_margin IS NULL;

DESCRIBE walmart;

-- Data cleaning
-- Clean unit price to remove $ and convert its type into int.
UPDATE walmart
SET unit_price = replace(unit_price, "$","")
WHERE unit_price LIKE "$%";

ALTER TABLE walmart
MODIFY COLUMN unit_price FLOAT;

-- Added new date datatype column
ALTER TABLE walmart
ADD COLUMN order_date DATE;

UPDATE walmart
SET order_date = str_to_date(date, "%d-%m-%Y");

-- Added new time datatype column
ALTER TABLE walmart
ADD COLUMN order_time TIME;

UPDATE walmart
SET order_time = time_format(time, "%H:%i:%s");

-- Dropped older columns
 ALTER TABLE walmart
 DROP COLUMN date,
 DROP COLUMN time;
 
 -- Calculate total sales and add column
 ALTER TABLE walmart
 ADD COLUMN total_sales FLOAT;
 
 UPDATE walmart
 SET total_sales = unit_price * quantity;
 
SELECT * FROM walmart;

-- 1. Sales Performance

-- What is the total sales revenue generated by each branch?
SELECT Branch, round(SUM(total_sales), 2) total_sales_revenue
FROM walmart
GROUP BY Branch
ORDER BY total_sales_revenue DESC;

-- Which product category contributes the highest total sales?
SELECT category, round(SUM(total_sales), 2) total_sale
FROM walmart
GROUP BY category
ORDER BY total_sale DESC;

-- What are the top 10 highest-value invoices (by total amount)?
SELECT invoice_id, round(SUM(total_sales), 2) total_invoice_value
FROM walmart
GROUP BY invoice_id
ORDER BY total_invoice_value DESC
LIMIT 10;

-- Which city has the highest total revenue?
SELECT City, round(SUM(total_sales), 2) revenue
FROM walmart
GROUP BY City
ORDER BY revenue DESC
LIMIT 1;

-- What is the average unit price and quantity sold per branch?
SELECT Branch, round(AVG(unit_price), 2) avg_unit_price, round(AVG(quantity), 2) avg_quantity
FROM walmart
GROUP BY Branch;

-- 2. Time-Based Analysis

-- What are the total daily and monthly sales trends?
-- Daily sales
SELECT order_date, round(SUM(total_sales), 2) daily_sales
FROM walmart
GROUP BY order_date
ORDER BY order_date;

-- Monthly sales
SELECT month(order_date) months, round(SUM(total_sales), 2) monthly_sales
FROM walmart
GROUP BY month(order_date)
ORDER BY months;

-- During which hour of the day do most transactions occur?
SELECT hour(order_time) transaction_hour, COUNT(*) transaction_count 
FROM walmart
GROUP BY hour(order_time)
ORDER BY transaction_count DESC;

-- What day of the week sees the highest customer traffic?
SELECT dayname(order_date) days, COUNT(*) customer_count
FROM walmart
GROUP BY dayname(order_date)
ORDER BY customer_count DESC;

-- Compare weekday vs weekend sales — which performs better?
SELECT 
	CASE WHEN dayofweek(order_date) IN (1,7) THEN "Weekend"
	ELSE "Weekday" 
    END AS day_type,
round(SUM(total_sales), 2) sales
FROM walmart
GROUP BY day_type;

-- Which month recorded the highest average profit margin?
SELECT monthname(order_date) months, round(AVG(profit_margin), 2) avg_profit_margin
FROM walmart
GROUP BY monthname(order_date)
ORDER BY avg_profit_margin DESC;

-- 3. Payment and Profit Insights

-- Which payment method is used most frequently overall and by branch?
-- Overall
SELECT payment_method, COUNT(*) use_count
FROM walmart
GROUP BY payment_method
ORDER BY use_count DESC;

-- By branch
SELECT Branch, payment_method, COUNT(*) use_count
FROM walmart
GROUP BY Branch, payment_method
ORDER BY Branch, use_count DESC;

-- What is the average profit margin per payment method?
SELECT payment_method, round(AVG(profit_margin), 2) avg_profit_margin
FROM walmart
GROUP BY payment_method;

-- Identify the top 5 most profitable product categories.
SELECT category, round(AVG(profit_margin), 3) avg_profit
FROM walmart
GROUP BY category
ORDER BY avg_profit DESC
LIMIT 5;

-- Which combination of city and payment method yields the most revenue?
SELECT City, payment_method, round(SUM(total_sales), 2) revenue
FROM walmart
GROUP BY City, payment_method
ORDER BY revenue DESC;

-- How does the average transaction value differ across payment methods?
SELECT payment_method, round(AVG(total_sales), 2) avg_transaction_value
FROM walmart
GROUP BY payment_method
ORDER BY avg_transaction_value DESC;

-- 4. Customer & Rating Insights

-- What is the average rating for each branch?
SELECT Branch, round(AVG(rating), 2) avg_rating
FROM walmart
GROUP BY Branch
ORDER BY avg_rating DESC;

-- Do higher ratings correlate with higher profit margins?
SELECT round(AVG(rating), 2) avg_rating, round(AVG(profit_margin), 2) avg_profit_margin
FROM walmart;

-- Which product categories receive the highest average ratings?
SELECT category, round(AVG(rating), 2) avg_rating
FROM walmart
GROUP BY category
ORDER BY avg_rating DESC;

-- How do ratings vary across different payment methods?
SELECT payment_method, round(AVG(rating), 2) avg_rating
FROM walmart
GROUP BY payment_method
ORDER BY avg_rating DESC;

-- Are there specific cities or branches where customer satisfaction is below average?
SET @avg_rating :=
(SELECT round(AVG(rating), 2) FROM walmart);

SELECT @avg_rating;

SELECT City, Branch, @avg_rating, round(AVG(rating), 2) avg_branch_rating
		FROM walmart
		GROUP BY City, Branch
        HAVING avg_branch_rating < @avg_rating
		ORDER BY avg_branch_rating DESC;
        